// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBID0-Ot5AR7iB84cYdm1dq80ByqqlynkE',
    appId: '1:593070598197:web:5f2f0f749ad399f3ff297c',
    messagingSenderId: '593070598197',
    projectId: 'vitfoodz',
    authDomain: 'vitfoodz.firebaseapp.com',
    storageBucket: 'vitfoodz.appspot.com',
    measurementId: 'G-675QSB3HL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP1_izGZ_eTvPlICBFL8Fk_TfqhLWQySM',
    appId: '1:593070598197:android:f281b35c01fde04fff297c',
    messagingSenderId: '593070598197',
    projectId: 'vitfoodz',
    storageBucket: 'vitfoodz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgkeD6K8SS4YT3ze5xHqNNl0cx0h-5_MU',
    appId: '1:593070598197:ios:5028aaf52ad0b719ff297c',
    messagingSenderId: '593070598197',
    projectId: 'vitfoodz',
    storageBucket: 'vitfoodz.appspot.com',
    androidClientId: '593070598197-iroh27bqgj4cht77hev2a6g7mktm2h1j.apps.googleusercontent.com',
    iosClientId: '593070598197-lo5aesrt8rfiqghll7baainermrp77ip.apps.googleusercontent.com',
    iosBundleId: 'com.example.food',
  );
}
